// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tabtzfvazhqogqqkzndq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhYnR6ZnZhemhxb2dxcWt6bmRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjY2NzgsImV4cCI6MjA2MzI0MjY3OH0.SFnlrsmOWhrO_IzL1oMP4ZZdvRlZA1RoWdye9Has7oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);